services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - 5678:5678
    expose:
      - 5678
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_ENCRYPTION_KEY=your-encryption-key
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_SQLITE_POOL_SIZE=10
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/app/monorepo
      - ./apps/frontend:/app/apps/frontend
      - ./apps/backend:/app/apps/backend
      - ./tests:/app/tests

volumes:
  n8n_data: